version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: localdev
      POSTGRES_USER: localdev
      POSTGRES_DB: teams_dev
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
